version: 0.0
os: linux
files:
  - source: /
    overwrite: true
    destination: /var/www/html/laravel
    
hooks:
 AfterInstall:
    - location: scripts/set-permissions.sh
      timeout: 300
      runas: root
