version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/laravel
permissions:
  - object: /var/www/laravel
    pattern: "*"
    owner: www-data
    group: www-data
    mode: 755
permissions:
  - object: /var/www/laravel
    pattern: "bootstrap/cache"
    owner: www-data
    group: www-data
    mode: 777


